name: build bot.py
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: load content
              uses: actions/checkout@v3
              
            - name: load python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10' # install the python version needed

            - name: start bot
              env:
                TOKEN: ${{ secrets.TOKEN }}
                DUMP_CHANNEL: ${{ secrets.DUMP_CHANNEL }}
